name: Continuous Integration
on:
  pull_request:
jobs:
  bazel-source-inspection:
    runs-on: ubuntu-latest
    steps:
    - name: Check out VCS repository
      uses: actions/checkout@v3
    - name: Confirm Bazel files is formatted per "buildifier"
      uses: thompsonja/bazel-buildifier@v0.4.0
      with:
        # See https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md.
        warnings: -function-docstring,-module-docstring
        buildifier_version: 6.1.0
  build-test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out VCS repository
      uses: actions/checkout@v3
    - name: Build and test all Bazel targets
      uses: ./.github/actions/build-test
